name: Doctest package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  doctest-package:
    runs-on: ubuntu-latest

    env:
      INTERPRETER: python
      PIP: python -m pip

    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install local package
      run: make install-local-package
    - name: Doctest package
      run: make doctest-package