name: Lint package

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main", "tester/*"]
  pull_request:
    branches: ["main"]

jobs:
  lint-package:
    runs-on: ubuntu-latest

    env:
      INTERPRETER: python
      PIP: python -m pip

    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install local package
      run: make install-local-package
    - name: Install package linter
      run: make install-package-linter
    - name: Lint package
      run: make lint-package