name: Test package

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["main", "tester/*"]
  pull_request:
    branches: ["main"]

jobs:
  test-package:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name: [
          "ubuntu-python-3-8",
          "ubuntu-python-3-9",
          "ubuntu-python-3-10",
          "ubuntu-python-3-11",
          "ubuntu-python-3-12",

          "windows-python-3-8",
          "windows-python-3-9",
          "windows-python-3-10",
          "windows-python-3-11",
          "windows-python-3-12",

          "macos-python-3-8",
          "macos-python-3-9",
          "macos-python-3-10",
          "macos-python-3-11",
          "macos-python-3-12"
        ]

        include:
          - name: "ubuntu-python-3-8"
            python-version: "3.8"
            os: ubuntu-latest
          - name: "ubuntu-python-3-9"
            python-version: "3.9"
            os: ubuntu-latest
          - name: "ubuntu-python-3-10"
            python-version: "3.10"
            os: ubuntu-latest
          - name: "ubuntu-python-3-11"
            python-version: "3.11"
            os: ubuntu-latest
          - name: "ubuntu-python-3-12"
            python-version: "3.12"
            os: ubuntu-latest

          - name: "windows-python-3-8"
            python-version: "3.8"
            os: windows-latest
          - name: "windows-python-3-9"
            python-version: "3.9"
            os: windows-latest
          - name: "windows-python-3-10"
            python-version: "3.10"
            os: windows-latest
          - name: "windows-python-3-11"
            python-version: "3.11"
            os: windows-latest
          - name: "windows-python-3-12"
            python-version: "3.12"
            os: windows-latest

          - name: "macos-python-3-8"
            python-version: "3.8"
            os: macos-latest
          - name: "macos-python-3-9"
            python-version: "3.9"
            os: macos-latest
          - name: "macos-python-3-10"
            python-version: "3.10"
            os: macos-latest
          - name: "macos-python-3-11"
            python-version: "3.11"
            os: macos-latest
          - name: "macos-python-3-12"
            python-version: "3.12"
            os: macos-latest

    env:
      INTERPRETER: python
      PIP: python -m pip

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install local package
      run: make install-local-package
    - name: Install requirements
      run: make install-requirements && make install-test-requirements
    - name: Test package
      run: make test-package